//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: hello.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// 定义一个打招呼服务
///
/// Usage: instantiate `GreeterClient`, then call methods of this protocol to make API calls.
internal protocol GreeterClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: GreeterClientInterceptorFactoryProtocol? { get }

  func sayHello(
    _ request: HelloRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<HelloRequest, HelloReply>
}

extension GreeterClientProtocol {
  internal var serviceName: String {
    return "Greeter"
  }

  /// SayHello 方法
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sayHello(
    _ request: HelloRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<HelloRequest, HelloReply> {
    return self.makeUnaryCall(
      path: "/Greeter/SayHello",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

internal protocol GreeterClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'sayHello'.
  func makeSayHelloInterceptors() -> [ClientInterceptor<HelloRequest, HelloReply>]
}

internal final class GreeterClient: GreeterClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: GreeterClientInterceptorFactoryProtocol?

  /// Creates a client for the Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: GreeterClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

